### Lab 6 - Preparing and Balancing For Classification
1. Part 1: Completed for you already. Reiview it.
2. Part 2: <font color='red'>dealing with imbalances</font> to avoid creating a bias when building a classifier

#2. Dealing with imbalances 
By completing the previous section, you have arranged the data, cleaned it, made the teacher happy, spent some sweat and blood, and reduced the number of values down to three so we can perform classification. At this stage, we have three classes (happiness, satisfaction, trust), each taking three values. Classifiers would be built for each class separately. That is, given a class such as happiness, you would build a classifier that identifies its outcome (happy? unhappy? neutral?) given the features. The problem is that there is some imbalance because 'neutral' is less prevalent. Normally, we'd deal with imbalances by a mix of under- and over-sampling (i.e. generating synthetic data). But there are other approaches out there. This section completes our class discussion by showing you two such approaches.

# Milestone 4

**Part 1**

In [19]:
# Import pandas and numpy libraries
import pandas as pd
import numpy as np

In [20]:
'''
4.1. Load studyData_cleaned.csv into a dataframe called data.

Find the calss distribution for the attribute Trust in data
'''
data = pd.read_csv('studyData_cleaned.csv')
data.head()

,Happiness,Satisfaction,Trust,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,happy,satisfied,distrust,0,-2,2,1,2,0,2,...,1,1,0,0,2,0,2,0,-1,1
1,happy,satisfied,trust,-2,-2,2,-1,2,2,2,...,-2,2,2,-2,2,1,1,1,-2,0
2,happy,satisfied,trust,1,-1,0,-2,1,-1,1,...,1,1,1,0,1,0,1,1,-1,1
3,happy,satisfied,trust,1,-2,1,-2,2,-1,2,...,1,1,1,0,1,-1,2,0,-2,2
4,happy,satisfied,trust,2,-1,0,-2,2,-2,2,...,1,0,0,0,1,-2,0,1,-2,2

In [21]:
'''
4.2. Now, Transform Trust into binary classification by combining distrust and neutral into a single class.
Display the new class distribution
Hint: Use one-hot encoding as 1 means Trust and 0 means NoTrust
'''
from sklearn.preprocessing import OneHotEncoder

data['Trust']=data['Trust'].replace({'trust':1, 'distrust':0,'neutral':0})
#data.Trust.value_counts()
data

,Happiness,Satisfaction,Trust,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,happy,satisfied,0,0,-2,2,1,2,0,2,...,1,1,0,0,2,0,2,0,-1,1
1,happy,satisfied,1,-2,-2,2,-1,2,2,2,...,-2,2,2,-2,2,1,1,1,-2,0
2,happy,satisfied,1,1,-1,0,-2,1,-1,1,...,1,1,1,0,1,0,1,1,-1,1
3,happy,satisfied,1,1,-2,1,-2,2,-1,2,...,1,1,1,0,1,-1,2,0,-2,2
4,happy,satisfied,1,2,-1,0,-2,2,-2,2,...,1,0,0,0,1,-2,0,1,-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850,unhappy,unsatisfied,0,1,-1,-1,2,2,0,-2,...,-2,0,1,2,2,0,0,0,1,0
5851,happy,satisfied,1,0,1,0,1,1,2,1,...,-1,1,0,-1,0,1,1,0,-2,0
5852,neutral,neutral,0,1,-1,0,1,0,-1,1,...,1,1,0,1,1,-1,1,1,0,1
5853,happy,satisfied,0,1,-2,0,0,1,-1,1,...,-1,1,0,-1,0,-2,1,0,-1,0
5854,happy,satisfied,1,1,2,2,-2,1,-2,2,...,0,2,2,-2,2,0,2,2,-2,2

In [22]:
'''
Import resample from sklearn.utils
'''
from sklearn.utils import resample

In [23]:
'''
4.3. Separate the majority and minority classes into two dataframes data_majority and data_minority and print them
'''
#Not clear until I read the questions after that the majority and minority class is based on trust.

data_majority=data[data['Trust']==1]

data_minority=data[data['Trust']==0]
data_minority

,Happiness,Satisfaction,Trust,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,happy,satisfied,0,0,-2,2,1,2,0,2,...,1,1,0,0,2,0,2,0,-1,1
5,happy,satisfied,0,-1,-1,1,1,2,1,1,...,1,1,1,1,1,1,0,1,-1,0
6,happy,satisfied,0,2,-2,2,-2,2,2,2,...,2,2,0,0,-2,-2,2,0,-2,2
7,happy,neutral,0,0,1,0,1,0,1,1,...,-1,0,0,1,0,1,1,1,0,0
8,neutral,neutral,0,0,-1,2,0,2,0,2,...,0,0,1,1,1,-1,2,2,-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5847,neutral,neutral,0,-1,0,0,-1,1,0,0,...,-1,0,0,-1,0,1,0,1,-2,1
5848,unhappy,unsatisfied,0,0,-1,1,0,1,-1,0,...,-1,-1,1,-1,1,0,1,1,0,-1
5850,unhappy,unsatisfied,0,1,-1,-1,2,2,0,-2,...,-2,0,1,2,2,0,0,0,1,0
5852,neutral,neutral,0,1,-1,0,1,0,-1,1,...,1,1,0,1,1,-1,1,1,0,1
5853,happy,satisfied,0,1,-2,0,0,1,-1,1,...,-1,1,0,-1,0,-2,1,0,-1,0

In [24]:
'''
4.4 Upsample the minority class using resample method with reproducible results
Store the results into data_minority_upsampled
'''
#There are 3037 in the majority class, and 2818 in the minority.
#Randomly sample 219 rows of the minority class
#add them back to the minority, 

sampledf= data_minority.sample(n=219)
sampledf
frames=[data_minority, sampledf]
data_minority_upsampled=pd.concat(frames)

In [25]:
'''
4.5. display data_minority_upsampled
'''
data_minority_upsampled

,Happiness,Satisfaction,Trust,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,happy,satisfied,0,0,-2,2,1,2,0,2,...,1,1,0,0,2,0,2,0,-1,1
5,happy,satisfied,0,-1,-1,1,1,2,1,1,...,1,1,1,1,1,1,0,1,-1,0
6,happy,satisfied,0,2,-2,2,-2,2,2,2,...,2,2,0,0,-2,-2,2,0,-2,2
7,happy,neutral,0,0,1,0,1,0,1,1,...,-1,0,0,1,0,1,1,1,0,0
8,neutral,neutral,0,0,-1,2,0,2,0,2,...,0,0,1,1,1,-1,2,2,-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,unhappy,unsatisfied,0,0,-1,1,-1,0,0,1,...,-1,2,0,1,1,0,0,1,1,0
2834,unhappy,unsatisfied,0,1,2,1,-1,2,-1,-2,...,2,-2,2,1,-1,-2,-2,1,1,2
2610,happy,neutral,0,0,1,0,0,1,2,0,...,-1,-1,1,1,0,2,0,-1,-1,0
1667,unhappy,unsatisfied,0,0,-1,1,0,0,-1,1,...,0,0,1,0,-1,0,0,-1,0,1
4209,unhappy,unsatisfied,0,0,-1,0,1,2,0,1,...,0,0,0,0,1,-1,1,1,0,0

In [26]:
'''
4.6. Now, combine majority class with upsampled minority class into the new data frame called data_upsampled
Print the class distribtuion of the resulting data.
'''
classes=[data_majority, data_minority_upsampled]
data_upsampled=pd.concat(classes)
data_upsampled

,Happiness,Satisfaction,Trust,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
1,happy,satisfied,1,-2,-2,2,-1,2,2,2,...,-2,2,2,-2,2,1,1,1,-2,0
2,happy,satisfied,1,1,-1,0,-2,1,-1,1,...,1,1,1,0,1,0,1,1,-1,1
3,happy,satisfied,1,1,-2,1,-2,2,-1,2,...,1,1,1,0,1,-1,2,0,-2,2
4,happy,satisfied,1,2,-1,0,-2,2,-2,2,...,1,0,0,0,1,-2,0,1,-2,2
9,happy,satisfied,1,1,-2,0,-1,1,-1,1,...,1,1,0,-1,1,-1,1,1,-2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2720,unhappy,unsatisfied,0,0,-1,1,-1,0,0,1,...,-1,2,0,1,1,0,0,1,1,0
2834,unhappy,unsatisfied,0,1,2,1,-1,2,-1,-2,...,2,-2,2,1,-1,-2,-2,1,1,2
2610,happy,neutral,0,0,1,0,0,1,2,0,...,-1,-1,1,1,0,2,0,-1,-1,0
1667,unhappy,unsatisfied,0,0,-1,1,0,0,-1,1,...,0,0,1,0,-1,0,0,-1,0,1
4209,unhappy,unsatisfied,0,0,-1,0,1,2,0,1,...,0,0,0,0,1,-1,1,1,0,0

In [27]:
'''
4.7. Display new class counts of Trust
'''
data_upsampled.Trust.value_counts()

1    3037
0    3037
Name: Trust, dtype: int64

**Part 2**
Random Undersampling of Data Majority

In [28]:
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import warnings

In [29]:
data.columns

Index(['Happiness', 'Satisfaction', 'Trust', 'cp17i020', 'cp17i021',
       'cp17i022', 'cp17i023', 'cp17i024', 'cp17i025', 'cp17i026', 'cp17i027',
       'cp17i028', 'cp17i029', 'cp17i030', 'cp17i031', 'cp17i032', 'cp17i033',
       'cp17i034', 'cp17i035', 'cp17i036', 'cp17i037', 'cp17i038', 'cp17i039',
       'cp17i040', 'cp17i041', 'cp17i042', 'cp17i043', 'cp17i044', 'cp17i045',
       'cp17i046', 'cp17i047', 'cp17i048', 'cp17i049', 'cp17i050', 'cp17i051',
       'cp17i052', 'cp17i053', 'cp17i054', 'cp17i055', 'cp17i056', 'cp17i057',
       'cp17i058', 'cp17i059', 'cp17i060', 'cp17i061', 'cp17i062', 'cp17i063',
       'cp17i064', 'cp17i065', 'cp17i066', 'cp17i067', 'cp17i068', 'cp17i069'],
      dtype='object')

In [30]:
'''
4.8. Create a dataframe data_undersampled from data by moving "Trust" as the first column in the new dataframe.
'''

trusted=data['Trust']
data.drop('Trust', axis=1, inplace=True)
#data

data_undersampled=data
data_undersampled.insert(0, 'Trust', trusted)

In [31]:
'''
4.9. Display the restructured new dataframe data_undersampled.
'''
data_undersampled

,Trust,Happiness,Satisfaction,cp17i020,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,0,happy,satisfied,0,-2,2,1,2,0,2,...,1,1,0,0,2,0,2,0,-1,1
1,1,happy,satisfied,-2,-2,2,-1,2,2,2,...,-2,2,2,-2,2,1,1,1,-2,0
2,1,happy,satisfied,1,-1,0,-2,1,-1,1,...,1,1,1,0,1,0,1,1,-1,1
3,1,happy,satisfied,1,-2,1,-2,2,-1,2,...,1,1,1,0,1,-1,2,0,-2,2
4,1,happy,satisfied,2,-1,0,-2,2,-2,2,...,1,0,0,0,1,-2,0,1,-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850,0,unhappy,unsatisfied,1,-1,-1,2,2,0,-2,...,-2,0,1,2,2,0,0,0,1,0
5851,1,happy,satisfied,0,1,0,1,1,2,1,...,-1,1,0,-1,0,1,1,0,-2,0
5852,0,neutral,neutral,1,-1,0,1,0,-1,1,...,1,1,0,1,1,-1,1,1,0,1
5853,0,happy,satisfied,1,-2,0,0,1,-1,1,...,-1,1,0,-1,0,-2,1,0,-1,0
5854,1,happy,satisfied,1,2,2,-2,1,-2,2,...,0,2,2,-2,2,0,2,2,-2,2

In [32]:
'''
4.10. Split data_undersampled into two dataframes of features (X) consisting of all columns
of data_undersampled except "Trust" and target (y) consisting of target column "Trust"
'''
y=data_undersampled['Trust']
data_undersampled.drop('Trust', axis=1, inplace=True)
X=data_undersampled

In [33]:
'''
4.11. Split train-test data into X_train, X_test, y_train, y_test
'''
x_train,x_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=42)

In [34]:
'''
4.12. summarize class distribution of y_train
'''
y_train.value_counts()

1    2137
0    1961
Name: Trust, dtype: int64

In [38]:
'''
4.13. Define undersampling strategy 
Create undersample using RandomUnderSampler method using sampling_strategy as "majority" 
'''
#X=np.arange(X)
#from imblearn.under_sampling import RandomUnderSampler
underSample= RandomUnderSampler(sampling_strategy='majority', random_state=42)
x_res,y_res=underSample.fit_resample(X,y)

In [39]:
'''
4.14. Creat X_train_under, y_train_under from X_train and y_train using undersample.fit_resample
'''
X_train, y_train, X_test, y_test=train_test_split(x_res,y_res, test_size=0.3, random_state=42)

In [40]:
'''
4.15. Summarize class distribution of y_train_under after undersampling
'''
y_train.value_counts()

Happiness  Satisfaction  cp17i020  cp17i021  cp17i022  cp17i023  cp17i024  cp17i025  cp17i026  cp17i027  cp17i028  cp17i029  cp17i030  cp17i031  cp17i032  cp17i033  cp17i034  cp17i035  cp17i036  cp17i037  cp17i038  cp17i039  cp17i040  cp17i041  cp17i042  cp17i043  cp17i044  cp17i045  cp17i046  cp17i047  cp17i048  cp17i049  cp17i050  cp17i051  cp17i052  cp17i053  cp17i054  cp17i055  cp17i056  cp17i057  cp17i058  cp17i059  cp17i060  cp17i061  cp17i062  cp17i063  cp17i064  cp17i065  cp17i066  cp17i067  cp17i068  cp17i069
unhappy    unsatisfied    0         0         0         0        0          0        0          0         0         0        0          0         0         0         0         0        0          0         0         0         0         0         0         0        0          0         0         0         0         0         0         0         0         0        0          0         0         0         0         0         0         0        0          0         0         0         0        0          0        0           2
                          2         1         2         2        2         -2        0         -2        -2        -1        2          1         0         1         1        -1        0         -2        -2        -2         2         0         2         2        2         -2         0         0         1         2         2        -1         1         1        1          1        -1        -1         2         2        -2        -1        1          1         1        -2        -1        2          1        1           1
happy      satisfied      1        -2         1         0        1         -2        2         -2         0         0        2         -2         1         1         0        -2        2         -2         0         0         2        -2         2         1        1         -1         1        -2        -1        -1         1        -2         2        -1        2         -1         1        -2        -2         0         1         0        2         -1         1        -2         1        2         -1        0           1
                                                       -1        1          0        1         -1         1        -1        1         -2         1         0         1         0        1         -2         2        -1         0        -1         1        -1        0         -1        -1        -1        -1        -2         1        -1        -1         1        1          1         1        -1         0         0         1         1        1          0         1         0         1        1         -2        0           1
                                                                                                                    0        1         -2        -1        -1         1         1        1         -2         2        -1        -1        -2         2        -2        2          0        -1        -2        -2        -2         1        -1         2        -2        1          2         0        -2        -2        -2        -1         0        1         -1        -1         1         0        2         -2        2           1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
neutral    neutral        1        -2         0         1        2          2        1          0         0         1        1         -1         0         1         1         1        1          1        -2         0         1        -1        -1         1        0          0         1         1         1        -1         1        -2         1         1        0          1         1         0         1         0        -1         1        0          0         1         1         2        0          1        0           1
                                                        2        2         -2        2         -1         0        -2        2         -2         2         1         2        -2        2         -2         0        -2         2        -2        -1         1        0         -2         1         1         0         2         2        -2        -1         1        1          0         1         0         1         1         2         2        0          0         1        -2         1        0          0        1           1
                                              1        -2        1          0        1         -2         1        -1        1         -2         1         0        -1        -1        1         -2         1         0         1        -2         1        -2        1         -2        -1        -2        -2        -2         1        -2         2        -2        1          1         1        -2        -2        -1         0         1        1         -2         1        -1         1        1         -2        1           1
                                                       -1        1         -2        1         -1         1        -1        1         -1         0         0         1         1        1         -2         1        -2         1        -1         1         0        1         -1         1        -1        -1        -1         1        -2         2         0        1          2         1        -1        -1         1         0         1        0         -1         1         0         1        1         -1        1           1
happy      neutral       -1        -2        -1         2        1          0        2         -2         0         0        0         -2         2         2         2         1        2         -2        -1         0         0        -2         0         2        1         -1         2        -2         1        -2        -1        -2         2         0        0          2         2        -1         1         0        -2         2        0          0         1         1         2        1          1        1           1
Length: 1690, dtype: int64

**Part 3** SMOTE

In [41]:
'''
SMOTE - Synthetic Minority Oversampling Technique
With SMOTE, the minority class is over-sampled by creating “synthetic” examples 
rather than by over-sampling with replacement
'''
# import SMOTE oversampling and other necessary libraries 
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [42]:
'''
Display X and y created from dataframe data_undersampled of numeric data.
'''
X = data_undersampled.iloc[:,3:]
y = data_undersampled.iloc[:,0]

In [43]:
X

,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,cp17i027,cp17i028,cp17i029,cp17i030,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
0,-2,2,1,2,0,2,0,1,0,0,...,1,1,0,0,2,0,2,0,-1,1
1,-2,2,-1,2,2,2,-2,1,-2,0,...,-2,2,2,-2,2,1,1,1,-2,0
2,-1,0,-2,1,-1,1,-1,1,-1,1,...,1,1,1,0,1,0,1,1,-1,1
3,-2,1,-2,2,-1,2,0,1,-2,1,...,1,1,1,0,1,-1,2,0,-2,2
4,-1,0,-2,2,-2,2,0,2,-2,2,...,1,0,0,0,1,-2,0,1,-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850,-1,-1,2,2,0,-2,-1,-2,0,0,...,-2,0,1,2,2,0,0,0,1,0
5851,1,0,1,1,2,1,-1,1,0,1,...,-1,1,0,-1,0,1,1,0,-2,0
5852,-1,0,1,0,-1,1,-1,-1,0,1,...,1,1,0,1,1,-1,1,1,0,1
5853,-2,0,0,1,-1,1,-1,0,-1,2,...,-1,1,0,-1,0,-2,1,0,-1,0
5854,2,2,-2,1,-2,2,-2,1,-2,2,...,0,2,2,-2,2,0,2,2,-2,2

In [44]:
y

0         happy
1         happy
2         happy
3         happy
4         happy
         ...
5850    unhappy
5851      happy
5852    neutral
5853      happy
5854      happy
Name: Happiness, Length: 5855, dtype: object

In [45]:
'''
Split train-test data
'''
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30)

In [46]:
X_train

,cp17i021,cp17i022,cp17i023,cp17i024,cp17i025,cp17i026,cp17i027,cp17i028,cp17i029,cp17i030,...,cp17i060,cp17i061,cp17i062,cp17i063,cp17i064,cp17i065,cp17i066,cp17i067,cp17i068,cp17i069
47,-2,1,0,1,-2,2,-2,1,0,1,...,1,1,0,0,0,-1,1,-1,-2,1
4319,-2,1,-1,1,-2,2,-1,1,-1,0,...,-1,1,1,-1,1,-2,1,1,-2,0
4608,-2,2,0,0,-2,2,-2,0,-1,2,...,-1,2,2,-2,1,0,2,1,0,-1
3304,0,0,0,0,0,1,-1,0,0,1,...,1,0,0,0,0,0,0,0,0,0
1789,-2,1,0,2,0,1,-1,2,-2,0,...,1,2,2,-1,1,1,2,0,-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3827,-2,0,1,2,-1,2,-1,1,0,1,...,0,1,0,1,0,-1,1,0,-1,-1
2185,-1,1,-2,1,-1,1,-1,1,-1,0,...,1,1,1,-1,1,0,1,-1,-2,2
964,-1,0,-1,1,1,0,-2,1,0,1,...,1,0,0,-1,1,0,0,-1,1,-1
1597,-1,1,-1,1,0,1,-2,2,-1,1,...,-2,-1,2,-1,1,0,0,1,-2,-1
3373,1,1,-1,2,2,-1,-2,1,0,1,...,-1,-2,1,0,1,1,-1,0,-2,0

In [47]:
'''
summarize class distribution of y_train
'''
print("Before oversampling: ",Counter(y_train))

Before oversampling:  Counter({'happy': 2275, 'neutral': 1224, 'unhappy': 599})

In [48]:
# define oversampling strategy as SMOTE
oversample = SMOTE()

In [49]:
# fit and apply the transform
X_train_SMOTE, y_train_SMOTE = oversample.fit_resample(X_train, y_train)

In [50]:
# summarize class distribution
print("After oversampling: ",Counter(y_train_SMOTE))

After oversampling:  Counter({'neutral': 2275, 'happy': 2275, 'unhappy': 2275})

# 2. Dealing with imbalances 

We have three classes (happiness, satisfaction, trust), each taking three values. Classifiers would be built for each class separately. That is, given a class such as happiness, you would build a classifier that identifies its outcome (happy? unhappy? neutral?) given the features. The problem is that there is some imbalance because 'neutral' is less prevalent. Normally, we'd deal with imbalances by a mix of under- and over-sampling (i.e. generating synthetic data). But there are other approaches out there. This section completes our class discussion by showing you two such approaches.

2.1 Careful design of sub-samples for bootstrap aggregating (i.e. bagging)
There are many ways to dealing with imbalances. In the class, we mostly discuss under- and over-sampling (by creating synthetic data). In this section, we complement the class discussion by looking at Bootstrap aggregating), also commonly known as bagging. In short, a decision tree is very sensitive to the specific data on which you train it which means that it can easily overfit. Bagging will instead divide the data into many random sub-samples, build a decision tree on each one, and combine the predictions made by each tree. It's a good approach to avoid over-fitting, not an approach to deal with imbalance. But we'll see in that it can be extended to deal with both over-fitting and class imbalance.

Because you end up with several trees, it's an ensemble method, i.e. the prediction is given by looking at the consensus among many classifiers. Note that bagging is not limited to trees. You could use it on any machine learning algorithm that has an easy tendency to overfit.

The following code uses scikit-learn's built-in bagging process. It's just an example of how bagging works. You can run it, because these variables should exist in your data.

In [52]:
import pandas
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
seed=7
kfold = model_selection.KFold(n_splits=10)# random_state=seed)
# list the predictive attributes. This example just takes 4 but you have more!
featureNames=[]
for i in range(20,70):
    featureNames.append('cp17i0'+str(i))
X = data[featureNames]#separate the attributes as X...
Y = data[['Satisfaction']] #pick the class you want to predict

# we make a 'bag of classifiers'. We specify that each classifier is a tree and we use 20 trees.
model = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=10, random_state=seed)
results = model_selection.cross_val_score(model, X, Y.values.ravel(), cv=kfold)
print(results.mean())

0.5366339955077156

# Milestone 5: Grad Students only (5 points)

Read the syntaxes and examples of SMOTE, SMOTENC, and SMOTEN from the following:

https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTE.html

https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTENC.html

https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTEN.html


Implement any **TWO** SMOTE techniques presented in the following article for oversampling Imbalance Data in dataframe data and display the results of using the resampled data in any ML model of your choice.

https://towardsdatascience.com/5-smote-techniques-for-oversampling-your-imbalance-data-b8155bdbe2b5

# End